//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapsAliveTourBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Html {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Html() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapsAliveTourBuilder.Html", typeof(Html).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///
        ///  var _gaq = _gaq || [];
        ///  _gaq.push([&apos;_setAccount&apos;, &apos;UA-1038667-1&apos;]);
        ///  _gaq.push([&apos;_setDomainName&apos;, &apos;.mapsalive.com&apos;]);
        ///  _gaq.push([&apos;_trackPageview&apos;]);
        ///
        ///  (function() {
        ///    var ga = document.createElement(&apos;script&apos;); ga.type = &apos;text/javascript&apos;; ga.async = true;
        ///    ga.src = (&apos;https:&apos; == document.location.protocol ? &apos;https://ssl&apos; : &apos;http://www&apos;) + &apos;.google-analytics.com/ga.js&apos;;
        ///    var s = document.getElementsByTagName(&apos;script&apos;)[0]; s.parentNode.insertBefore(ga,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnalyticsScript {
            get {
                return ResourceManager.GetString("AnalyticsScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Tip:&lt;/b&gt; .
        /// </summary>
        internal static string BannerDimensionTip0 {
            get {
                return ResourceManager.GetString("BannerDimensionTip0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Height to &lt;b&gt;{0}&lt;/b&gt; to minimize blank space on the right side of this banner image..
        /// </summary>
        internal static string BannerDimensionTip1 {
            get {
                return ResourceManager.GetString("BannerDimensionTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  For an exact fit and optimal image quality, upload a banner image that is {0} x {1}..
        /// </summary>
        internal static string BannerDimensionTip2 {
            get {
                return ResourceManager.GetString("BannerDimensionTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family:Arial, Helvetica, Verdana, Sans-Serif;font-size:14px&quot;&gt;&lt;a href=&quot;https://www.mapsalive.com&quot;&gt;www.mapsalive.com&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;Tour &lt;b&gt;{0}&lt;/b&gt; has no pages yet.&lt;br/&gt;&lt;br/&gt;&lt;span style=&quot;font-size:11px;&quot;&gt;To add a page to this tour, click the &lt;b&gt;Add Page&lt;/b&gt; button in the Tour Builder.&lt;/span&gt;&lt;/div&gt;.
        /// </summary>
        internal static string HtmlForDefaultPage {
            get {
                return ResourceManager.GetString("HtmlForDefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try out your tour.&amp;nbsp;&amp;nbsp;To return to the Tour Builder, click &lt;b&gt;Back&lt;/b&gt;..
        /// </summary>
        internal static string PreviewerInstructions {
            get {
                return ResourceManager.GetString("PreviewerInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the fields below.&amp;nbsp;&amp;nbsp;We will not ask you for any other information in order to create your account..
        /// </summary>
        internal static string RegisterText0 {
            get {
                return ResourceManager.GetString("RegisterText0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script defer src=&quot;http://server1.opentracker.net/?site=www.mapsalive.com&quot;&gt;&lt;/script&gt;&lt;noscript&gt;&lt;a href=&quot;http://www.opentracker.net&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;http://img.opentracker.net/?cmd=nojs&amp;site=www.mapsalive.com&quot; alt=&quot;page counter&quot; border=&quot;0&quot;&gt;&lt;/a&gt; &lt;/noscript&gt;.
        /// </summary>
        internal static string TrackerScript {
            get {
                return ResourceManager.GetString("TrackerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your MapsAlive account has been created.&lt;br/&gt;Use it FREE for 30 days!&lt;br/&gt;&lt;br/&gt;Click the button below to create your first tour..
        /// </summary>
        internal static string WelcomeMessage1 {
            get {
                return ResourceManager.GetString("WelcomeMessage1", resourceCulture);
            }
        }
    }
}
