//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapsAliveTourBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapsAliveTourBuilder.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tour.
        /// </summary>
        internal static string ButtonCreateTour {
            get {
                return ResourceManager.GetString("ButtonCreateTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string CategoryKindName {
            get {
                return ResourceManager.GetString("CategoryKindName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CategoryKindTitle {
            get {
                return ResourceManager.GetString("CategoryKindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction has been declined. Please verify that you have entered correct data in all fields..
        /// </summary>
        internal static string CCAuthResultMessage2 {
            get {
                return ResourceManager.GetString("CCAuthResultMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the information does not appear to be valid. Please verify that you have entered correct data in all fields..
        /// </summary>
        internal static string CCDataInvalid {
            get {
                return ResourceManager.GetString("CCDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expiration date is in the past. Please verify that it matches the date on your credit card..
        /// </summary>
        internal static string CCExpDateInvalid {
            get {
                return ResourceManager.GetString("CCExpDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card number is not valid. Please verify that it matches the number on your credit card..
        /// </summary>
        internal static string CCNumberInvalid {
            get {
                return ResourceManager.GetString("CCNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circles require exactly 4 values (x, y, r, 0).
        /// </summary>
        internal static string CirclenNeedsFourValues {
            get {
                return ResourceManager.GetString("CirclenNeedsFourValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click mouse to pin window.
        /// </summary>
        internal static string DefaultPinPopupMessage {
            get {
                return ResourceManager.GetString("DefaultPinPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        internal static string KindName {
            get {
                return ResourceManager.GetString("KindName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotspot.
        /// </summary>
        internal static string KindNameSlide {
            get {
                return ResourceManager.GetString("KindNameSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines require 2 points (4 values) or more.
        /// </summary>
        internal static string LineNeedsFourValues {
            get {
                return ResourceManager.GetString("LineNeedsFourValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygons require 3 points (6 values) or more.
        /// </summary>
        internal static string PolygonNeedsSixValues {
            get {
                return ResourceManager.GetString("PolygonNeedsSixValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner image will appear here.
        /// </summary>
        internal static string PreviewMissingBannerImageHelp {
            get {
                return ResourceManager.GetString("PreviewMissingBannerImageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map image will appear here .
        /// </summary>
        internal static string PreviewMissingMapImageHelp {
            get {
                return ResourceManager.GetString("PreviewMissingMapImageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo will appear here.
        /// </summary>
        internal static string PreviewMissingViewImageHelp {
            get {
                return ResourceManager.GetString("PreviewMissingViewImageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangles require exactly 2 points (4 values).
        /// </summary>
        internal static string RectangleNeedsFourValues {
            get {
                return ResourceManager.GetString("RectangleNeedsFourValues", resourceCulture);
            }
        }
    }
}
